#!/bin/bash

# check presence of build tools
make -v > /dev/null 2>&1
if [[ $? != 0 ]]; then
    echo 'Please install build tools.'
    echo -n 'Press Enter to stop installation...'
    read
    exit
fi

# check presence of JDK
java -version > /dev/null 2>&1
if [[ $? != 0 ]]; then
    echo 'Please install Java Development Kit.'
    echo -n 'Press Enter to stop installation...'
    read
    exit
fi

# get gems directory
pushd "`pwd`" > /dev/null
cd "`dirname "$0"`/.gems"
GEMS=`pwd`
popd > /dev/null

# install gems
function install() { echo; echo "sudo gem install" $(printf '%q' "$1"); sudo gem install "$1"; }

install rhomobile-debug
install "$GEMS"/rhodes-[0-9]*.gem
install "$GEMS"/rhoelements-[0-9]*.gem
install "$GEMS"/rhoconnect-[0-9]*.gem
install "$GEMS"/rhoconnect-adapters-[0-9]*.gem
install rhodes-translator
