#!/bin/bash

echo "Enter ruby version: "
read rubyver

make > /dev/null 2> /dev/null

if [ $? != 2 ]
then
  echo 'Please install building tools'
  exit;
fi

java 1> /dev/null 2> /dev/null

if [ $? != 0 ]
then
  echo 'Please install java development kit'
  exit;
fi
 
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

if [ -z "$rubyver" ]
then
  echo 'Please enter valid ruby version'
  exit; 
else
  rvm use $rubyver
fi

ruby -v

echo "Enter 1 if you do not want use \"sudo\" for install gems"
echo "Enter 2 if you want use \"sudo\" command prefix for install gems"
read usesudo

if [ $usesudo != 2 ]
then
  echo "Install rhomobile debugger"
  gem install rhomobile-debug

  echo "Install rhodes gem"
  gem install "/Volumes/Motorola RhoMobile Suite Installer/.gems/rhodes-3.4.1.3.0.beta.gem"	

  echo "Install rhodes translator gem"
  gem install "/Volumes/Motorola RhoMobile Suite Installer/.gems/rhoelements-2.1.1.3.0.beta.gem"

  echo "Install rhoconnect gem"
  gem install "/Volumes/Motorola RhoMobile Suite Installer/.gems/rhoconnect-3.2.1.gem"

  echo "Install rhoconnect adapters gem"
  gem install "/Volumes/Motorola RhoMobile Suite Installer/.gems/rhoconnect-adapters-1.0.3.gem"

  echo "Install rhodes translator gem"
  gem install rhodes-translator
else
  echo "Install rhomobile debugger"
  sudo gem install rhomobile-debug

  echo "Install rhodes gem"
  sudo gem install "/Volumes/Motorola RhoMobile Suite Installer/.gems/rhodes-3.4.1.3.0.beta.gem"	

  echo "Install rhodes translator gem"
  sudo gem install "/Volumes/Motorola RhoMobile Suite Installer/.gems/rhoelements-2.1.1.3.0.beta.gem"

  echo "Install rhoconnect gem"
  sudo gem install "/Volumes/Motorola RhoMobile Suite Installer/.gems/rhoconnect-3.2.1.gem"

  echo "Install rhoconnect adapters gem"
  sudo gem install "/Volumes/Motorola RhoMobile Suite Installer/.gems/rhoconnect-adapters-1.0.3.gem"

  echo "Install rhodes translator gem"
  sudo gem install rhodes-translator
fi

