#!/bin/bash

# check presence of npm
npm --version > /dev/null 2>&1
if [[ $? != 0 ]]; then
    echo 'Please install Node.js (https://nodejs.org/dist/latest/node-v0.12.7.pkg).'
    echo -ne "\nPress Enter to stop rhoconnect-push installation..."
    read
    exit
fi

# get rps directory
pushd "`pwd`" > /dev/null
cd "`dirname "$0"`/.rps"
RPS=`pwd`
popd > /dev/null

# add 'sudo' to 'npm install'?
INSTALL="npm install --global"
while true; do
    echo -ne "\nDo you want to install rhoconnect-push with 'sudo' command prefix? [Yn]  "
    read SUDO
    if [[ "$SUDO" == "" || "$SUDO" == "y" || "$SUDO" == "Y" ]]; then
        INSTALL="sudo "$INSTALL
        break;
    fi
    if [[ "$SUDO" == "n" || "$SUDO" == "N" ]]; then
        break;
    fi
done

# install rhoconnect-push
function install() { echo; echo $INSTALL $(printf '%q' "$1"); $INSTALL "$1"; }

install "$RPS"/rhoconnect-push-[0-9]*.tgz

# keep terminal window to inspect output
echo -ne '\nPress Enter to exit...'
read
