#!/bin/bash

# load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
    . "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]]; then
    . "/usr/local/rvm/scripts/rvm"
else
    echo 'Please install RVM.'
    echo -n 'Press Enter to stop installation...'
    read
    exit
fi

# select Ruby to work with
echo
echo "Select Ruby version to start RhoStudio:"
RUBIES=`rvm list strings`
select RUBY in $RUBIES; do
    [[ -n "$RUBY" ]] && break;
done
echo
rvm use "$RUBY"
ruby -v

sleep 2

exec "/Applications/Motorola RhoStudio/macosx.cocoa.x86/RhoStudio.app/Contents/MacOS/RhoStudio"
