#!/bin/bash

# load RVM into a shell session *as a function*
RVM=true
if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
    . "$HOME/.rvm/scripts/rvm"
elif [[ -s "/usr/local/rvm/scripts/rvm" ]]; then
    . "/usr/local/rvm/scripts/rvm"
else
    RVM=false
fi

# select Ruby to work with
if $RVM; then
    echo
    echo "Select Ruby version to start RhoStudio:"
    RUBIES=`rvm list gemsets strings`
    select RUBY in $RUBIES; do
        [[ -n "$RUBY" ]] && break;
    done
    echo
    rvm use "$RUBY"
fi
ruby -v

sleep 2

exec "/Applications/Motorola RhoStudio/macosx.cocoa.x86_64/RhoStudio.app/Contents/MacOS/RhoStudio"
