# rake script

require 'date'
require 'fileutils'
load 'jake.rb'

$majorVer = "2"
$minorVer = "0"
$miniVer  = "0"
$betaVer  = "3"

$isRhodesBeta   = true
$isConnBeta     = false
$isAdapterBeta  = false
$isElementsBeta = true

$isMotorolaBeta = true

$rhoelemetsgem     = "C:/Android/installer/script/rhoelements-2.0.0.beta.9.gem"
$nsisPath          = "C:/Program Files (x86)/NSIS/makensis.exe"
$rubyPath          = "C:/Android/rhosync/ruby"
$rubyInstallPath   = "C:/Android/Installer/package/ruby"
$installScript     = "rhostudio.nsi"
$installMotoScript = "rhostudio-moto.nsi"
$commonName        = "RhoStudioInstaller"
$extWinExe         = '.exe'
$extOsxExe         = '.dmg'
$config            = Jake.config(File.open("installer.yml"))
$package_dir       = "../package"
$eclipseLauncherJar = '/Users/sv/rhomobile/eclipse/plugins/org.eclipse.equinox.launcher_1.1.1.R36x_v20101122_1400.jar'
$pluginExport = '/Users/sv/rhomobile/rhostudio/rhogen-wizard/plugin_export.xml'

namespace "installer" do

    def deployRhoElements2App
      $app_config = Hash.new
      $app_config["extpaths"] = Array.new

      chdir $package_dir
      rho_elements_dst_dir = "RhoElements2"
      rm_rf rho_elements_dst_dir
      require "rhoelements"
      rho_elements_src_dir = File.expand_path(File.join($rhodes_extensions[0], "..", "..", "RhoElements2"))
      puts "source Rhoelements2 directory: " + rho_elements_src_dir
      cp_r rho_elements_src_dir, rho_elements_dst_dir
      chdir File.dirname(__FILE__)
    end

    def exportPlugin
        destination = File.expand_path File.join($package_dir, 'eclipse')
        destinationJarGlob = File.join(destination, 'plugins', 'com.rhomobile.rhostudio_*.jar')
        FileUtils.rm Dir.glob(destinationJarGlob)
        system "java -jar #{$eclipseLauncherJar} -application org.eclipse.ant.core.antRunner -buildfile #{$pluginExport} -Ddestination=#{destination}"
    end

    def prepareNsisScript(installDir)
       FileUtils.cp_r $installScript, installDir
       script_name = File.join(installDir, $installScript)
       install_script = File.read(script_name)
       install_script = install_script.gsub(/%NSIS_SCRIPT_PATH%/, File.expand_path("./").gsub("\/","\\"))
       File.open(script_name, "w") { |file| file.puts install_script }

       # script for motorola
       FileUtils.cp_r $installMotoScript, installDir
       script_name = File.join(installDir, $installMotoScript)
       install_script = File.read(script_name)
       install_script = install_script.gsub(/%NSIS_SCRIPT_PATH%/, File.expand_path("./").gsub("\/","\\"))
       File.open(script_name, "w") { |file| file.puts install_script }
    end

    def runNsisScript(installScript)
       prepareNsisScript($package_dir)
       chdir $package_dir
       Jake.run2 $nsisPath, [installScript], {:nowait => false}
       chdir File.dirname(__FILE__)
    end

    def renameInstaller(installerPrefix)
       puts 'add version to build file'
       installerName = ""
       currTime = Time.now
       currDate = currTime.strftime("%d%m%Y%H%M")

       installerName = $commonName + $majorVer.to_s + "." + $minorVer.to_s + "." + $miniVer +  installerPrefix + $extWinExe

       puts 'new installer file name: ' + installerName
       File.rename($commonName + $extWinExe, installerName) 
    end

    def changeRubyFolder()
        #copy ruby folder
        puts 'start change ruby folder'
        FileUtils.rm_rf "./eclipse/configuration/.setting"
        #FileUtils.rm_rf $rubyInstallPath      
        #FileUtils.cp_r $rubyPath, $rubyInstallPath
    end

    def installMotoGems(isElementsBeta)
        if File.exist? $rhoelemetsgem
          Jake.run2 "gem", ["uninstall", "rhoelements", "-a"], {:nowait => false} 
          Jake.run2 "gem", ["install", $rhoelemetsgem], {:nowait => false} 
       else
          puts 'Rhoelements gem not found [' + $rhoelemetsgem + ']'
          exit
       end
    end

    def installGems(isRhodesBeta, isConnBeta, isAdapterBeta)
        Jake.run2 "gem", ["uninstall", "rhomobile-debug", "-a"], {:nowait => false} 
        Jake.run2 "gem", ["uninstall", "rhodes", "-a"], {:nowait => false} 
        Jake.run2 "gem", ["uninstall", "rhoconnect", "-a"], {:nowait => false}       
        Jake.run2 "gem", ["uninstall", "rhoconnect-adapters", "-a"], {:nowait => false} 
        Jake.run2 "gem", ["uninstall", "rhodes-translator", "-a"], {:nowait => false} 
        Jake.run2 "gem", ["uninstall", "rhoelements", "-a"], {:nowait => false} 
        Jake.run2 "gem", ["uninstall", "mspec", "-a"], {:nowait => false} 

        Jake.run2 "gem", ["install", "rhomobile-debug"], {:nowait => false} 
        Jake.run2 "gem", ["install", "rhodes-translator"], {:nowait => false} 
        Jake.run2 "gem", ["install", "mspec"], {:nowait => false} 

        if isRhodesBeta == false
          Jake.run2 "gem", ["install", "rhodes"], {:nowait => false} 
        else
          Jake.run2 "gem", ["install", "rhodes", "--pre"], {:nowait => false} 
        end

	      if isConnBeta == false
          Jake.run2 "gem", ["install", "rhoconnect"], {:nowait => false}       
        else
          Jake.run2 "gem", ["install", "rhoconnect", "--pre"], {:nowait => false}       
        end

        if isAdapterBeta == false
          Jake.run2 "gem", ["install", "rhoconnect-adapters"], {:nowait => false} 
        else
          Jake.run2 "gem", ["install", "rhoconnect-adapters", "--pre"], {:nowait => false} 
        end
    end  

    namespace "release" do
      task :gems do
        puts 'release - reinstall gems task'
        installGems(false, false, false)
        changeRubyFolder()
        deployRhoElements2App()
      end

      task :nsis => "gems" do 
        puts 'release - start build nsis script: ' +  $installScript
        runNsisScript($installScript)
      end

      task :rename => "nsis" do
        puts 'release - start rename task'
        renameInstaller("")
      end

    end

    namespace "beta" do
      task :gems do
        installGems(true, true, true)
        changeRubyFolder()
        deployRhoElements2App()
      end

      task :nsis => "gems" do 
        puts 'start build nsis script: ' +  $installScript
        runNsisScript($installScript)
      end

      task :rename => "nsis" do
        renameInstaller(".beta" + $betaVer)
      end

    end

    namespace "user" do
      task :gems do
        installGems($isRhodesBeta, $isConnBeta, $isAdapterBeta)
        changeRubyFolder()
        deployRhoElements2App()
      end

      task :nsis => "gems" do 
        puts 'start build nsis script: ' +  $installScript
        runNsisScript($installScript)
      end

      task :rename => "nsis" do
        renameInstaller(".beta" + $betaVer)
      end

    end

    namespace "motorola" do
      task :gems do
        puts 'release - reinstall gems task'        
        installGems($isRhodesBeta, $isConnBeta, $isAdapterBeta)
        installMotoGems($isElementsBeta)
        changeRubyFolder()
        deployRhoElements2App()
      end

      task :nsis => "gems" do 
        puts 'release - start build nsis script: ' +  $installMotoScript
        runNsisScript($installMotoScript)
      end

      task :rename => "nsis" do
        puts 'release - start rename task'

        if $isMotorolaBeta == true
           renameInstaller(".beta" + $betaVer)
        else
           renameInstaller("")
        end
      end
    end

    ########################################################

    task :release => "release:rename" do
    end

    task :beta => "beta:rename" do
    end

    task :user => "user:rename" do
    end

    task :motorola => "motorola:rename" do
    end

    task :test do
      deployRhoElements2App
      exportPlugin
    end

end
